/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "funcionesBanco.h"

bool_t
xdr_argumentos (XDR *xdrs, argumentos *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->saldo))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->monto))
		 return FALSE;
	return TRUE;
}
