/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FUNCIONESBANCO_H_RPCGEN
#define _FUNCIONESBANCO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct argumentos {
	double saldo;
	double monto;
};
typedef struct argumentos argumentos;

#define FUNCIONESBANCO 0x20000001
#define Banco_Servicios 1

#if defined(__STDC__) || defined(__cplusplus)
#define Retirar 1
extern  int * retirar_1(argumentos *, CLIENT *);
extern  int * retirar_1_svc(argumentos *, struct svc_req *);
#define Depositar 2
extern  int * depositar_1(argumentos *, CLIENT *);
extern  int * depositar_1_svc(argumentos *, struct svc_req *);
extern int funcionesbanco_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Retirar 1
extern  int * retirar_1();
extern  int * retirar_1_svc();
#define Depositar 2
extern  int * depositar_1();
extern  int * depositar_1_svc();
extern int funcionesbanco_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_argumentos (XDR *, argumentos*);

#else /* K&R C */
extern bool_t xdr_argumentos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FUNCIONESBANCO_H_RPCGEN */
