/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "funcionesBanco.h"

int *
retirar_1_svc(argumentos *argp, struct svc_req *rqstp)
{
	static int  result;
	double saldo =  argp->saldo;
	double monto = argp->monto;	
	if(monto<=saldo){
		result = 1; // bien
	}else{
		result = 0; // mal
	}
	return &result;
}

int *
depositar_1_svc(argumentos *argp, struct svc_req *rqstp)
{
	static int  result;

	double saldo =  argp->saldo;
	double monto = argp->monto;

	if(monto > 0){
		result = 1; // bien
	}else{
		result = 0; // mal
	}
	return &result;
}
